const StudyEvidence = (() => {
  const evidenceCategories = [
    { id: "all", label: "전체" },
    { id: "rosuzet-direct", label: "로수젯 직접/인접" },
    { id: "rosuvastatin-ezetimibe", label: "Rosu+Eze 전략" },
    { id: "ezetimibe-outcome", label: "Ezetimibe outcome" },
    { id: "statin-foundation", label: "Statin foundation" },
    { id: "pcsk9-inclisiran", label: "PCSK9 / Inclisiran" },
    { id: "bempedoic", label: "Bempedoic acid" },
    { id: "tg-residual-risk", label: "TG / residual risk" },
    { id: "korean-epidemiology", label: "국내 역학/합의" }
  ];

  const evidenceAtlas = [
    {
      id: "eroica",
      title: "EROICA",
      year: "2026",
      category: "rosuzet-direct",
      productRelevance: "direct",
      design: "Korean multicentre, prospective, open-label, single-arm",
      population: "T2DM + dyslipidaemia, statin monotherapy despite LDL-C >=70 mg/dL",
      intervention: "Rosuzet 10/2.5 mg once daily for 12 weeks",
      comparator: "No parallel control",
      endpoint: "LDL-C <70 mg/dL at Week 12",
      result: "FAS 586명에서 62.3%가 LDL-C <70 mg/dL 달성, LDL-C 26.0% 감소, adherence 97.5%.",
      pmUse: "T2DM 환자에서 10/2.5 mg switch story의 핵심 직접 근거.",
      limitations: "Peer-reviewed publication은 확인됐지만 single-arm, open-label, 12주 연구라 장기 outcome claim으로 확대 금지.",
      sourceTier: "A",
      sourceUrl: "https://pubmed.ncbi.nlm.nih.gov/41190361/"
    },
    {
      id: "mrs-roze",
      title: "MRS-ROZE",
      year: "2016",
      category: "rosuzet-direct",
      productRelevance: "direct",
      design: "Korean phase III, randomized, double-blind, 8-week",
      population: "Primary hypercholesterolemia, 407 randomized",
      intervention: "Ezetimibe 10 mg + rosuvastatin 5/10/20 mg",
      comparator: "Same-dose rosuvastatin monotherapy",
      endpoint: "Percent change in LDL-C and lipid parameters",
      result: "Combination achieved greater LDL-C reduction than rosuvastatin alone; reported LDL-C reduction range 56-63%.",
      pmUse: "로수젯 lipid efficacy와 DM/MetS subgroup story의 foundational evidence.",
      limitations: "Surrogate lipid endpoint 중심 8주 연구.",
      sourceTier: "A",
      sourceUrl: "https://pubmed.ncbi.nlm.nih.gov/27506635/"
    },
    {
      id: "low-dose-r25-e10",
      title: "R2.5 + E10 Phase III",
      year: "2021",
      category: "rosuzet-direct",
      productRelevance: "direct",
      design: "Korean randomized, double-blind, multicentre phase III, 8-week",
      population: "Hypercholesterolemia, 279 randomized",
      intervention: "Rosuvastatin 2.5 mg + ezetimibe 10 mg",
      comparator: "E10, R2.5, R5 monotherapy",
      endpoint: "Percent LDL-C change at Week 8",
      result: "R2.5+E10 LDL-C -45.7% vs R5 -38.9%; low/moderate risk target attainment 100% in combination arm.",
      pmUse: "10/2.5 mg을 초기 병용·lower statin exposure 옵션으로 설명.",
      limitations: "Outcome trial이 아니며 저·중등도 위험군 중심 해석 필요.",
      sourceTier: "A",
      sourceUrl: "https://pubmed.ncbi.nlm.nih.gov/34429197/"
    },
    {
      id: "rembrandt",
      title: "REMBRANDT",
      year: "2025/2026",
      category: "rosuzet-direct",
      productRelevance: "direct",
      design: "Phase IV randomized open-label active-controlled trial",
      population: "T2DM + mixed dyslipidemia with hypertriglyceridemia, 146 enrolled",
      intervention: "Rosuzet 10/5 mg",
      comparator: "Suvast rosuvastatin 10 mg",
      endpoint: "LDL-C and TG control, lipid profile",
      result: "ClinicalTrials.gov record is completed; Hanmi reported improvement in LDL-C, non-HDL-C, ApoB and lipid profile.",
      pmUse: "T2DM + high TG mixed dyslipidemia에서 10/5 mg early-combination story.",
      limitations: "ClinicalTrials.gov에는 posted results 없음. 학회/회사 발표와 논문화 여부를 계속 확인해야 함.",
      sourceTier: "B/C",
      sourceUrl: "https://clinicaltrials.gov/study/NCT04700436"
    },
    {
      id: "switch",
      title: "SWITCH",
      year: "2025",
      category: "rosuzet-direct",
      productRelevance: "strategy",
      design: "Korean multicentre prospective observational study",
      population: "Stroke patients on statin monotherapy with LDL-C >=70 mg/dL",
      intervention: "Switch to rosuvastatin plus ezetimibe 5/10, 10/10, or 20/10 mg",
      comparator: "Pre-switch statin monotherapy baseline",
      endpoint: "LDL-C <70 mg/dL at 6 months",
      result: "994 follow-up completers 중 71.2%가 6개월 LDL-C <70 mg/dL 달성.",
      pmUse: "Neurology/stroke segment에서 switch-in 실사용 근거.",
      limitations: "관찰연구이며 stricter target <55 mg/dL 또는 <70 mg/dL + 50% 감소 달성은 별도 해석 필요.",
      sourceTier: "A",
      sourceUrl: "https://pubmed.ncbi.nlm.nih.gov/41225467/"
    },
    {
      id: "rosetta-stroke",
      title: "ROSETTA-Stroke",
      year: "2023",
      category: "rosuvastatin-ezetimibe",
      productRelevance: "strategy",
      design: "Randomized, open-label, controlled trial",
      population: "Recent ischemic stroke within 90 days, 584 patients",
      intervention: "Rosuvastatin 10 mg + ezetimibe 10 mg",
      comparator: "Rosuvastatin 20 mg",
      endpoint: ">=50% LDL-C reduction at 90 days",
      result: "Combination arm achieved >=50% LDL-C reduction more often than high-intensity rosuvastatin monotherapy.",
      pmUse: "Stroke secondary prevention에서 statin 증량 대비 ezetimibe 추가 전략.",
      limitations: "90일 lipid endpoint 중심. 장기 clinical outcome claim은 제한.",
      sourceTier: "A",
      sourceUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC10250871/"
    },
    {
      id: "racing",
      title: "RACING main",
      year: "2022",
      category: "rosuvastatin-ezetimibe",
      productRelevance: "strategy",
      design: "Korean randomized open-label non-inferiority trial",
      population: "ASCVD, 3,780 patients",
      intervention: "Rosuvastatin 10 mg + ezetimibe 10 mg",
      comparator: "Rosuvastatin 20 mg",
      endpoint: "3-year CV death, major CV events, or nonfatal stroke",
      result: "Combination therapy was non-inferior and achieved LDL-C <70 mg/dL more often with fewer intolerance-related changes.",
      pmUse: "10/10 mg secondary prevention strategy의 중심 근거.",
      limitations: "Open-label, Korean ASCVD population, treatment strategy evidence.",
      sourceTier: "A",
      sourceUrl: "https://pubmed.ncbi.nlm.nih.gov/35863366/"
    },
    {
      id: "racing-vhr",
      title: "RACING very-high-risk analysis",
      year: "2023",
      category: "rosuvastatin-ezetimibe",
      productRelevance: "strategy",
      design: "Post hoc analysis of RACING",
      population: "ASCVD patients stratified by very-high-risk status",
      intervention: "Rosuvastatin 10 mg + ezetimibe 10 mg",
      comparator: "Rosuvastatin 20 mg",
      endpoint: "3-year composite CV outcome and LDL-C metrics",
      result: "Combination strategy results were consistent in very-high-risk and non-very-high-risk groups.",
      pmUse: "Very-high-risk objection 대응과 <55 mg/dL discussion backup.",
      limitations: "Post hoc subgroup analysis.",
      sourceTier: "A",
      sourceUrl: "https://pubmed.ncbi.nlm.nih.gov/37531130/"
    },
    {
      id: "racing-elderly",
      title: "RACING elderly analysis",
      year: "2023",
      category: "rosuvastatin-ezetimibe",
      productRelevance: "strategy",
      design: "Post hoc age-stratified RACING analysis",
      population: "ASCVD patients aged >=75 vs <75 years",
      intervention: "Rosuvastatin 10 mg + ezetimibe 10 mg",
      comparator: "Rosuvastatin 20 mg",
      endpoint: "3-year composite outcome, LDL-C, intolerance",
      result: "Elderly subgroup showed comparable CV outcome with lower intolerance-related discontinuation or dose reduction.",
      pmUse: "Elderly/polypharmacy segment에서 tolerability discussion.",
      limitations: "Subgroup analysis, not elderly-only prospective trial.",
      sourceTier: "A",
      sourceUrl: "https://www.jacc.org/doi/10.1016/j.jacc.2023.02.007"
    },
    {
      id: "racing-pci",
      title: "RACING PCI analysis",
      year: "2023",
      category: "rosuvastatin-ezetimibe",
      productRelevance: "strategy",
      design: "Post hoc analysis after PCI",
      population: "ASCVD patients after percutaneous coronary intervention",
      intervention: "Rosuvastatin 10 mg + ezetimibe 10 mg",
      comparator: "Rosuvastatin 20 mg",
      endpoint: "3-year outcome and LDL-C goal attainment",
      result: "Post-PCI subgroup findings supported the main RACING strategy.",
      pmUse: "Interventional cardiology/account targeting backup.",
      limitations: "Post hoc subgroup analysis.",
      sourceTier: "A",
      sourceUrl: "https://pubmed.ncbi.nlm.nih.gov/37090440/"
    },
    {
      id: "racing-diabetes",
      title: "RACING diabetes subgroup",
      year: "2024",
      category: "rosuvastatin-ezetimibe",
      productRelevance: "strategy",
      design: "RACING subgroup analysis",
      population: "ASCVD with diabetes",
      intervention: "Rosuvastatin 10 mg + ezetimibe 10 mg",
      comparator: "Rosuvastatin 20 mg",
      endpoint: "LDL-C <70 mg/dL and composite outcome",
      result: "Reviews and subgroup reports describe higher LDL-C goal attainment with comparable clinical outcomes.",
      pmUse: "T2DM + ASCVD에서 RACING과 EROICA를 연결.",
      limitations: "Subgroup source 확인과 원논문 citation mapping 필요.",
      sourceTier: "B",
      sourceUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC12428817/"
    },
    {
      id: "i-rosette",
      title: "I-ROSETTE",
      year: "2018",
      category: "rosuvastatin-ezetimibe",
      productRelevance: "class",
      design: "Korean phase III randomized double-blind active-controlled trial",
      population: "Hypercholesterolemia, 396 randomized",
      intervention: "Ezetimibe 10 mg + rosuvastatin 5/10/20 mg",
      comparator: "Rosuvastatin 5/10/20 mg monotherapy",
      endpoint: "Adjusted mean LDL-C percent change at Week 8",
      result: "Ezetimibe/rosuvastatin combinations lowered LDL-C more than rosuvastatin monotherapy and improved goal attainment.",
      pmUse: "동일성분 class evidence와 competitor education.",
      limitations: "타 제품 개발 연구이므로 로수젯 브랜드 claim으로 직접 사용 금지.",
      sourceTier: "A",
      sourceUrl: "https://pubmed.ncbi.nlm.nih.gov/29402522/"
    },
    {
      id: "t2dm-phase4",
      title: "High ASCVD-risk T2DM phase IV",
      year: "2023",
      category: "rosuvastatin-ezetimibe",
      productRelevance: "class",
      design: "Randomized, multicentre, open, parallel phase IV",
      population: "T2DM with estimated 10-year ASCVD risk >=7.5%",
      intervention: "Rosuvastatin 10 mg + ezetimibe 10 mg",
      comparator: "Rosuvastatin 20 mg",
      endpoint: "LDL-C change rate at Week 24",
      result: "Combination was non-inferior and numerically/superior for several lipid target metrics.",
      pmUse: "Endocrinology에서 moderate-intensity statin + ezetimibe rationale.",
      limitations: "Open-label, lipid/metabolic endpoints.",
      sourceTier: "A",
      sourceUrl: "https://pubmed.ncbi.nlm.nih.gov/38043782/"
    },
    {
      id: "dm-inflammation",
      title: "Rosu/Eze insulin sensitivity study",
      year: "2024",
      category: "rosuvastatin-ezetimibe",
      productRelevance: "class",
      design: "Randomized comparative study",
      population: "T2DM + dyslipidemia, 101 patients",
      intervention: "Rosuvastatin 5 mg + ezetimibe 10 mg",
      comparator: "Rosuvastatin 5 mg",
      endpoint: "Lipid profile, HOMA-IR, vascular inflammatory markers",
      result: "Combination improved LDL-C more, but no additional insulin sensitivity or vascular inflammation effect was shown.",
      pmUse: "긍정/중립 결과를 함께 학습하는 balanced evidence.",
      limitations: "Small study, surrogate biomarkers.",
      sourceTier: "A",
      sourceUrl: "https://pubmed.ncbi.nlm.nih.gov/38173371/"
    },
    {
      id: "rosetta-meta",
      title: "Rosu/Eze vs quadruple-dose rosuvastatin meta-analysis",
      year: "2024",
      category: "rosuvastatin-ezetimibe",
      productRelevance: "class",
      design: "Systematic review and meta-analysis",
      population: "RCTs comparing moderate-intensity rosu/eze vs higher-dose rosuvastatin",
      intervention: "Moderate-intensity rosuvastatin/ezetimibe",
      comparator: "Quadruple-dose rosuvastatin monotherapy",
      endpoint: "LDL-C efficacy and tolerability",
      result: "Supports comparable or better lipid-lowering with combination strategy in selected comparisons.",
      pmUse: "Rule-of-six와 statin escalation limitation 교육.",
      limitations: "Included-study heterogeneity and publication mix.",
      sourceTier: "A",
      sourceUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC10774651/"
    },
    {
      id: "improve-it",
      title: "IMPROVE-IT",
      year: "2015",
      category: "ezetimibe-outcome",
      productRelevance: "class",
      design: "Randomized double-blind outcomes trial",
      population: "Recent ACS, 18,144 patients",
      intervention: "Simvastatin 40 mg + ezetimibe 10 mg",
      comparator: "Simvastatin 40 mg",
      endpoint: "Composite CV outcome over median 6 years",
      result: "Ezetimibe addition lowered LDL-C further and improved cardiovascular outcomes.",
      pmUse: "Ezetimibe 추가의 class-level outcome 근거.",
      limitations: "Simvastatin-based trial, not rosuvastatin/ezetimibe direct evidence.",
      sourceTier: "A",
      sourceUrl: "https://pubmed.ncbi.nlm.nih.gov/26039521/"
    },
    {
      id: "sharp",
      title: "SHARP",
      year: "2011",
      category: "ezetimibe-outcome",
      productRelevance: "class",
      design: "Randomized double-blind placebo-controlled outcomes trial",
      population: "CKD, 9,270 patients",
      intervention: "Simvastatin 20 mg + ezetimibe 10 mg",
      comparator: "Placebo",
      endpoint: "Major atherosclerotic events",
      result: "Combination reduced major atherosclerotic events in advanced CKD.",
      pmUse: "CKD segment의 ezetimibe/statin class outcome context.",
      limitations: "Not rosuvastatin-based; CKD-specific population.",
      sourceTier: "A",
      sourceUrl: "https://pubmed.ncbi.nlm.nih.gov/21663949/"
    },
    {
      id: "ewtopia75",
      title: "EWTOPIA 75",
      year: "2019",
      category: "ezetimibe-outcome",
      productRelevance: "class",
      design: "Prospective randomized open-label blinded-endpoint trial",
      population: "Japanese adults >=75 years, elevated LDL-C, no CAD history",
      intervention: "Ezetimibe 10 mg",
      comparator: "Usual care",
      endpoint: "Composite atherosclerotic CV events",
      result: "Ezetimibe reduced primary outcome, but interpretation requires caution.",
      pmUse: "Elderly primary prevention discussion backup.",
      limitations: "Open-label, premature termination and follow-up issues.",
      sourceTier: "A",
      sourceUrl: "https://pubmed.ncbi.nlm.nih.gov/31434507/"
    },
    {
      id: "seas",
      title: "SEAS",
      year: "2008",
      category: "ezetimibe-outcome",
      productRelevance: "class",
      design: "Randomized double-blind trial",
      population: "Asymptomatic aortic stenosis",
      intervention: "Simvastatin 40 mg + ezetimibe 10 mg",
      comparator: "Placebo",
      endpoint: "Aortic stenosis progression and ischemic events",
      result: "LDL-C lowering did not change aortic stenosis progression; coronary events differed in some analyses.",
      pmUse: "LDL-C lowering claim이 모든 질환 progression claim으로 확장되지 않음을 교육.",
      limitations: "Aortic stenosis population, not dyslipidemia target-attainment setting.",
      sourceTier: "A",
      sourceUrl: "https://pubmed.ncbi.nlm.nih.gov/20425166/"
    },
    {
      id: "ctt-2005",
      title: "CTT 2005 meta-analysis",
      year: "2005",
      category: "statin-foundation",
      productRelevance: "context",
      design: "Prospective meta-analysis of 14 randomized statin trials",
      population: "90,056 participants",
      intervention: "Statin LDL-C lowering",
      comparator: "Control or less intensive therapy",
      endpoint: "Major vascular events per 1 mmol/L LDL-C reduction",
      result: "Established the proportional relationship between LDL-C reduction and vascular event reduction.",
      pmUse: "LDL-C lowering 자체의 causal evidence foundation.",
      limitations: "Statin-focused, older trial era.",
      sourceTier: "A",
      sourceUrl: "https://pubmed.ncbi.nlm.nih.gov/16214597/"
    },
    {
      id: "ctt-low-risk",
      title: "CTT low-risk meta-analysis",
      year: "2012",
      category: "statin-foundation",
      productRelevance: "context",
      design: "Individual participant data meta-analysis",
      population: "27 randomized trials",
      intervention: "Statin or more intensive statin",
      comparator: "Control or less intensive therapy",
      endpoint: "Major vascular events by baseline risk",
      result: "LDL-C lowering reduced major vascular events across baseline risk categories.",
      pmUse: "Risk-based absolute benefit와 LDL-C lowering principle 교육.",
      limitations: "Absolute benefit depends on baseline risk.",
      sourceTier: "A",
      sourceUrl: "https://pubmed.ncbi.nlm.nih.gov/22607822/"
    },
    {
      id: "hps",
      title: "Heart Protection Study",
      year: "2002",
      category: "statin-secondary-prevention",
      productRelevance: "context",
      design: "Randomized placebo-controlled trial",
      population: "High-risk individuals, 20,536 adults",
      intervention: "Simvastatin 40 mg",
      comparator: "Placebo",
      endpoint: "Major vascular events",
      result: "Simvastatin reduced major vascular events across a broad high-risk population.",
      pmUse: "High-risk absolute benefit와 long-term treatment rationale.",
      limitations: "Simvastatin era, background therapy differs from current practice.",
      sourceTier: "A",
      sourceUrl: "https://pubmed.ncbi.nlm.nih.gov/12114036/"
    },
    {
      id: "prove-it",
      title: "PROVE IT-TIMI 22",
      year: "2004/2005",
      category: "statin-intensive-strategy",
      productRelevance: "context",
      design: "Randomized ACS trial",
      population: "Recent ACS, 4,162 patients",
      intervention: "Atorvastatin 80 mg",
      comparator: "Pravastatin 40 mg",
      endpoint: "Death, MI, UA hospitalization, revascularization, stroke",
      result: "Intensive LDL-C lowering after ACS improved clinical outcomes vs standard therapy.",
      pmUse: "ACS에서 early and intensive lipid lowering의 역사적 근거.",
      limitations: "Statin intensity comparison, not combination strategy.",
      sourceTier: "A",
      sourceUrl: "https://pubmed.ncbi.nlm.nih.gov/16356805/"
    },
    {
      id: "tnt",
      title: "TNT",
      year: "2005",
      category: "statin-intensive-strategy",
      productRelevance: "context",
      design: "Randomized double-blind trial",
      population: "Stable CHD, 10,001 patients",
      intervention: "Atorvastatin 80 mg",
      comparator: "Atorvastatin 10 mg",
      endpoint: "First major cardiovascular event",
      result: "Lower achieved LDL-C with high-dose atorvastatin reduced major cardiovascular events.",
      pmUse: "Stable CHD에서 lower LDL-C target rationale.",
      limitations: "Higher-dose statin adverse lab signal noted.",
      sourceTier: "A",
      sourceUrl: "https://pubmed.ncbi.nlm.nih.gov/15755765/"
    },
    {
      id: "sparcl",
      title: "SPARCL",
      year: "2006/2009",
      category: "statin-secondary-prevention",
      productRelevance: "context",
      design: "Randomized stroke/TIA secondary prevention trial",
      population: "Recent stroke or TIA without known CHD",
      intervention: "Atorvastatin 80 mg",
      comparator: "Placebo",
      endpoint: "Fatal or nonfatal stroke",
      result: "Atorvastatin reduced recurrent stroke and CV events across ischemic stroke subtypes.",
      pmUse: "Neurology에서 LDL-C lowering necessity를 설명하는 background.",
      limitations: "High-dose atorvastatin, not combination therapy.",
      sourceTier: "A",
      sourceUrl: "https://pubmed.ncbi.nlm.nih.gov/19228842/"
    },
    {
      id: "jupiter",
      title: "JUPITER",
      year: "2008",
      category: "statin-primary-prevention",
      productRelevance: "context",
      design: "Randomized placebo-controlled primary prevention trial",
      population: "LDL-C <130 mg/dL and hsCRP >=2 mg/L, 17,802 adults",
      intervention: "Rosuvastatin 20 mg",
      comparator: "Placebo",
      endpoint: "Major CV events",
      result: "Rosuvastatin reduced LDL-C, hsCRP and major cardiovascular events.",
      pmUse: "Rosuvastatin potency and primary prevention evidence context.",
      limitations: "Selected hsCRP population and early termination.",
      sourceTier: "A",
      sourceUrl: "https://pubmed.ncbi.nlm.nih.gov/18997196/"
    },
    {
      id: "woscops",
      title: "WOSCOPS long-term analysis",
      year: "1995/2017",
      category: "statin-primary-prevention",
      productRelevance: "context",
      design: "Randomized trial plus long-term follow-up analysis",
      population: "Primary prevention men with high LDL-C",
      intervention: "Pravastatin 40 mg",
      comparator: "Placebo",
      endpoint: "CHD and major adverse cardiovascular events",
      result: "LDL-C lowering reduced CHD and MACE, including LDL-C >=190 mg/dL subgroup.",
      pmUse: "Severe hypercholesterolemia and primary prevention foundation.",
      limitations: "Male-only historical cohort.",
      sourceTier: "A",
      sourceUrl: "https://pubmed.ncbi.nlm.nih.gov/28877913/"
    },
    {
      id: "fourier",
      title: "FOURIER",
      year: "2017",
      category: "pcsk9-inclisiran",
      productRelevance: "competitor",
      design: "Randomized double-blind placebo-controlled outcomes trial",
      population: "ASCVD, 27,564 patients on statin",
      intervention: "Evolocumab",
      comparator: "Placebo",
      endpoint: "Composite CV outcomes",
      result: "Evolocumab lowered LDL-C about 59% vs placebo and reduced CV events.",
      pmUse: "Very-high-risk goal failure에서 injectable competitor benchmark.",
      limitations: "Injection access, cost, reimbursement and patient preference matter.",
      sourceTier: "A",
      sourceUrl: "https://pubmed.ncbi.nlm.nih.gov/28304224/"
    },
    {
      id: "odyssey-outcomes",
      title: "ODYSSEY OUTCOMES",
      year: "2018",
      category: "pcsk9-inclisiran",
      productRelevance: "competitor",
      design: "Randomized double-blind placebo-controlled outcomes trial",
      population: "ACS 1-12 months earlier, 18,924 patients",
      intervention: "Alirocumab",
      comparator: "Placebo",
      endpoint: "CHD death, MI, ischemic stroke, or UA hospitalization",
      result: "Alirocumab reduced recurrent ischemic cardiovascular events after ACS.",
      pmUse: "Post-ACS high-risk escalation benchmark.",
      limitations: "Injectable PCSK9 mAb, not oral FDC.",
      sourceTier: "A",
      sourceUrl: "https://pubmed.ncbi.nlm.nih.gov/30403574/"
    },
    {
      id: "orion-10-11",
      title: "ORION-10/11",
      year: "2020",
      category: "pcsk9-inclisiran",
      productRelevance: "competitor",
      design: "Two randomized phase III trials",
      population: "ASCVD or risk equivalent with elevated LDL-C despite statins",
      intervention: "Inclisiran 284 mg on Day 1, Day 90, then every 6 months",
      comparator: "Placebo",
      endpoint: "LDL-C percent change at Day 510",
      result: "Inclisiran reduced LDL-C about 50% with twice-yearly maintenance dosing.",
      pmUse: "Adherence and dosing-frequency competitor story.",
      limitations: "LDL endpoint trial; CV outcome data must be tracked separately.",
      sourceTier: "A",
      sourceUrl: "https://pubmed.ncbi.nlm.nih.gov/32187462/"
    },
    {
      id: "clear-outcomes",
      title: "CLEAR Outcomes",
      year: "2023",
      category: "bempedoic",
      productRelevance: "competitor",
      design: "Randomized double-blind placebo-controlled outcomes trial",
      population: "Statin-intolerant patients with or at high risk for CVD",
      intervention: "Bempedoic acid 180 mg daily",
      comparator: "Placebo",
      endpoint: "Four-component MACE",
      result: "Bempedoic acid lowered MACE risk in statin-intolerant patients.",
      pmUse: "Statin intolerance discussion에서 emerging oral nonstatin benchmark.",
      limitations: "Gout, cholelithiasis and uric-acid/liver-enzyme signals require balanced discussion.",
      sourceTier: "A",
      sourceUrl: "https://doi.org/10.1056/NEJMoa2215024"
    },
    {
      id: "clear-primary",
      title: "CLEAR Outcomes primary prevention analysis",
      year: "2023",
      category: "bempedoic",
      productRelevance: "competitor",
      design: "Prespecified subgroup/analysis from CLEAR Outcomes",
      population: "Statin-intolerant primary prevention patients",
      intervention: "Bempedoic acid 180 mg daily",
      comparator: "Placebo",
      endpoint: "Composite CV events",
      result: "Primary prevention subgroup showed LDL-C and hsCRP lowering with event reduction signal.",
      pmUse: "High-risk primary prevention에서 future oral nonstatin watch.",
      limitations: "Subgroup framing; local approval/access determines practical relevance.",
      sourceTier: "A",
      sourceUrl: "https://pubmed.ncbi.nlm.nih.gov/37354546/"
    },
    {
      id: "reduce-it",
      title: "REDUCE-IT",
      year: "2019",
      category: "tg-residual-risk",
      productRelevance: "context",
      design: "Randomized double-blind placebo-controlled outcomes trial",
      population: "Statin-treated high CV risk, TG 135-499 mg/dL, LDL-C 41-100 mg/dL",
      intervention: "Icosapent ethyl 2 g twice daily",
      comparator: "Placebo",
      endpoint: "CV death, MI, stroke, revascularization, or UA",
      result: "Icosapent ethyl reduced ischemic events in patients with elevated TG on statins.",
      pmUse: "LDL-C 목표 이후 residual TG risk를 분리해 설명.",
      limitations: "EPA-specific data; AF/flutter and bleeding signals need balanced mention.",
      sourceTier: "A",
      sourceUrl: "https://pubmed.ncbi.nlm.nih.gov/30415628/"
    },
    {
      id: "strength",
      title: "STRENGTH",
      year: "2020",
      category: "tg-residual-risk",
      productRelevance: "context",
      design: "Randomized double-blind outcomes trial",
      population: "High CV risk, hypertriglyceridemia, low HDL-C",
      intervention: "EPA+DHA omega-3 carboxylic acids 4 g/day",
      comparator: "Corn oil",
      endpoint: "Major adverse CV events",
      result: "No significant CV benefit vs comparator.",
      pmUse: "Omega-3를 한 묶음으로 일반화하면 안 된다는 교육 포인트.",
      limitations: "Comparator and formulation debates remain.",
      sourceTier: "A",
      sourceUrl: "https://pubmed.ncbi.nlm.nih.gov/33190147/"
    },
    {
      id: "accord-lipid",
      title: "ACCORD-Lipid",
      year: "2010",
      category: "tg-residual-risk",
      productRelevance: "context",
      design: "Randomized trial in T2DM",
      population: "T2DM on simvastatin background",
      intervention: "Fenofibrate + simvastatin",
      comparator: "Simvastatin alone",
      endpoint: "Major CV events",
      result: "Overall CV benefit was not significant; high TG/low HDL subgroup generated discussion.",
      pmUse: "T2DM에서 TG/fibrate story를 LDL-C story와 분리.",
      limitations: "Subgroup interpretation caution.",
      sourceTier: "A",
      sourceUrl: "https://pubmed.ncbi.nlm.nih.gov/20228404/"
    },
    {
      id: "field",
      title: "FIELD",
      year: "2005",
      category: "tg-residual-risk",
      productRelevance: "context",
      design: "Randomized placebo-controlled trial",
      population: "T2DM",
      intervention: "Fenofibrate",
      comparator: "Placebo",
      endpoint: "Coronary events and CV outcomes",
      result: "Mixed results; microvascular and lipid subgroup discussion persisted.",
      pmUse: "Fibrate role를 LDL-C lowering과 분리해 학습.",
      limitations: "Background statin use and endpoint interpretation complexity.",
      sourceTier: "A",
      sourceUrl: "https://pubmed.ncbi.nlm.nih.gov/16310551/"
    },
    {
      id: "prominent",
      title: "PROMINENT",
      year: "2022",
      category: "tg-residual-risk",
      productRelevance: "context",
      design: "Randomized double-blind outcomes trial",
      population: "T2DM + hypertriglyceridemia + low HDL-C",
      intervention: "Pemafibrate",
      comparator: "Placebo",
      endpoint: "CV outcomes",
      result: "Pemafibrate did not improve CV outcomes despite TG lowering.",
      pmUse: "TG lowering alone과 CV outcome을 분리해서 설명.",
      limitations: "Drug-specific and population-specific result.",
      sourceTier: "A",
      sourceUrl: "https://pubmed.ncbi.nlm.nih.gov/36342113/"
    },
    {
      id: "korea-fact-sheet-2024",
      title: "Dyslipidemia Fact Sheet in South Korea 2024",
      year: "2025",
      category: "korean-epidemiology",
      productRelevance: "context",
      design: "KNHANES/NHIS-based epidemiologic report",
      population: "Korean adults aged >=20 years",
      intervention: "Not applicable",
      comparator: "Trend over time",
      endpoint: "Prevalence, awareness, treatment, control",
      result: "2016-2022 crude dyslipidemia prevalence 40.9% or 47.4% depending on HDL-C definition; 2022 hypercholesterolemia crude prevalence 27.4%.",
      pmUse: "시장 크기, diagnosis-treatment-control gap, public health context.",
      limitations: "Epidemiology, not product evidence.",
      sourceTier: "A",
      sourceUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC12488789/"
    },
    {
      id: "ksola-new-llt-2024",
      title: "2024 KSoLA Update on New Lipid-Lowering Agents",
      year: "2025",
      category: "korean-epidemiology",
      productRelevance: "competitor",
      design: "KSoLA update/consensus article",
      population: "Korean dyslipidemia practice context",
      intervention: "Inclisiran and bempedoic acid",
      comparator: "Existing lipid-lowering strategy",
      endpoint: "Practice update",
      result: "KSoLA published an update on new lipid-lowering agents including inclisiran and bempedoic acid.",
      pmUse: "Future competitor tracker와 guideline-update watch.",
      limitations: "Consensus/update article, not outcomes trial.",
      sourceTier: "A",
      sourceUrl: "https://e-jla.org/src/jla_citation_mail/jla-citation-category-2025.html"
    },
    {
      id: "ksola-secondary-2024",
      title: "2024 KSoLA Consensus on Secondary Dyslipidemia",
      year: "2024",
      category: "korean-epidemiology",
      productRelevance: "context",
      design: "KSoLA consensus",
      population: "Secondary dyslipidemia practice context",
      intervention: "Secondary cause evaluation",
      comparator: "Not applicable",
      endpoint: "Consensus statements",
      result: "Secondary causes and differential management of dyslipidemia were addressed by KSoLA.",
      pmUse: "환자 segment에서 secondary dyslipidemia를 놓치지 않게 하는 학습축.",
      limitations: "Not product evidence.",
      sourceTier: "A",
      sourceUrl: "https://e-jla.org/src/jla_citation_mail/jla-citation-category-2025.html"
    }
  ];

  const deepDiveIds = [
    "eroica",
    "rembrandt",
    "switch",
    "rosetta-stroke",
    "racing",
    "racing-vhr",
    "racing-elderly",
    "racing-pci",
    "low-dose-r25-e10",
    "mrs-roze"
  ];

  const getEvidenceById = (id) => evidenceAtlas.find((study) => study.id === id);

  const getEvidenceByCategory = (category) => {
    if (category === "all") {
      return evidenceAtlas;
    }
    return evidenceAtlas.filter((study) => study.category === category);
  };

  const directStudyDeepDives = deepDiveIds.map((id) => {
    const study = getEvidenceById(id);
    return {
      ...study,
      claimGuardrail: `${study.limitations} 근거 등급과 제품 직접성(${study.productRelevance})을 확인하고 확대 claim을 피한다.`
    };
  });

  return {
    directStudyDeepDives,
    evidenceAtlas,
    evidenceCategories,
    getEvidenceByCategory,
    getEvidenceById
  };
})();

globalThis.StudyEvidence = StudyEvidence;
