(() => {
  const libraryCategories = [
    { id: "lipid-basics", label: "지질 기초", focus: "LDL-C, non-HDL-C, ApoB, TG, Lp(a) 해석" },
    { id: "risk-stratification", label: "위험도 분류", focus: "ASCVD, 당뇨병, CKD, 뇌졸중, FH, risk enhancer" },
    { id: "guideline-workflow", label: "지침 Workflow", focus: "KSoLA, ESC/EAS, ACC/AHA, ADA 목표와 escalation" },
    { id: "treatment", label: "치료 전략", focus: "statin, ezetimibe, 로수젯, PCSK9, bempedoic, TG 치료" },
    { id: "safety", label: "안전성", focus: "SAMS, 간효소, 당뇨병, 신장, 임신, 상호작용" },
    { id: "special-populations", label: "특수 환자", focus: "T2DM, ACS, stroke, elderly, CKD, FH" },
    { id: "market", label: "시장/분류", focus: "WHO ATC, EPHMRA C10C, funnel, 경쟁구도" },
    { id: "field", label: "Field Execution", focus: "진료과 메시지, 반론 대응, claim guardrail" },
    { id: "evidence-reading", label: "논문 독해", focus: "PICO, endpoint, subgroup, noninferiority, RWE" },
    { id: "glossary", label: "용어 사전", focus: "PM 회의에서 바로 쓰는 핵심 약어" }
  ];

  const libraryModules = [
    module("ldl-c-core", "lipid-basics", "LDL-C가 1차 치료 목표인 이유", "동맥경화성 심혈관질환의 causal factor로 LDL-C 누적 노출이 해석된다.", ["위험군별 목표치를 먼저 잡고 baseline 대비 필요한 감소율을 계산한다.", "PM 메시지는 절대 LDL-C와 percent reduction을 함께 말해야 한다.", "LDL-C가 낮을수록 좋다는 표현은 지침 범위와 안전성 맥락을 같이 둔다."], "로수젯은 LDL-C gap이 큰 환자에서 dual inhibition 전략을 설명하기 쉽다.", "ESC/EAS·ACC/AHA·KSoLA 지침", "https://www.escardio.org/guidelines/clinical-practice-guidelines/all-esc-practice-guidelines/dyslipidaemias/"),
    module("non-hdl-c", "lipid-basics", "non-HDL-C 해석", "LDL-C 외 VLDL, remnant cholesterol까지 포함하는 atherogenic cholesterol 지표다.", ["TG가 높거나 당뇨병/비만이 있으면 LDL-C만으로 위험을 과소평가할 수 있다.", "non-HDL-C는 공복 여부 영향이 LDL-C보다 작아 실무 대화에 유용하다.", "LDL-C target 달성 후 residual risk 논의로 연결한다."], "TG 동반 환자에서 로수젯 메시지는 LDL-C 중심을 유지하되 non-HDL-C를 보조 지표로 둔다.", "KSoLA/ESC lipid marker framework", "https://new.lipid.or.kr/reference/guideline.php?boardid=guideline&category=&idx=1281&mode=view"),
    module("apob", "lipid-basics", "ApoB: particle number 관점", "ApoB는 atherogenic lipoprotein particle 수를 반영해 discordance 상황에서 유용하다.", ["LDL-C가 낮아도 ApoB가 높으면 particle burden이 남아 있을 수 있다.", "당뇨병, 대사증후군, 고TG에서는 ApoB 질문이 자주 나온다.", "국내 실무에서는 필수 검사라기보다 risk refinement 도구로 설명한다."], "ApoB 질문은 로수젯의 LDL-C lowering 메시지를 particle burden 논의로 확장하는 교육 포인트다.", "ESC/EAS lipid biomarker guidance", "https://www.escardio.org/guidelines/clinical-practice-guidelines/all-esc-practice-guidelines/dyslipidaemias/"),
    module("tg-remnant", "lipid-basics", "TG와 remnant cholesterol", "TG 자체보다 remnant-rich lipoprotein이 잔여위험 설명에 중요하다.", ["LDL-C가 목표에 가까워도 TG가 높으면 lifestyle, glycemic control, alcohol, secondary cause를 확인한다.", "fibrate/omega-3 논의는 LDL-C lowering claim과 분리한다.", "REDUCE-IT 같은 outcome 근거는 제제와 환자군을 엄격히 구분한다."], "로수젯은 TG 치료제가 아니라 LDL-C 중심 FDC라는 경계를 분명히 해야 한다.", "REDUCE-IT/KSoLA TG guidance", "https://pubmed.ncbi.nlm.nih.gov/30415628/"),
    module("lpa", "lipid-basics", "Lp(a) 고위험 신호", "Lp(a)는 유전적 영향이 큰 독립 위험인자로 조기 ASCVD나 가족력이 있을 때 확인 가치가 있다.", ["생활습관과 statin으로 크게 낮아지지 않는다.", "현재 치료 메시지는 LDL-C 등 수정 가능한 위험인자 최적화에 둔다.", "향후 Lp(a) 표적치료제는 update watch가 필요하다."], "Lp(a) 질문을 받으면 로수젯 claim으로 확대하지 말고 overall LDL-C burden 감소 전략으로 답한다.", "ESC prevention/lipid guidance", "https://www.escardio.org/guidelines"),
    module("hdl-c", "lipid-basics", "HDL-C는 치료 표적이 아니다", "낮은 HDL-C는 위험 marker지만 약물로 HDL-C만 올리는 전략은 outcome benefit이 일관되지 않았다.", ["PM 대화에서 HDL-C 상승 claim은 매우 조심한다.", "운동, 체중, 금연 같은 lifestyle 메시지와 연결한다.", "LDL-C target first 원칙을 흐리지 않는다."], "로수젯 교육에서는 HDL-C보다 LDL-C target gap과 dual mechanism에 집중한다.", "CTT/niacin/CETP outcome history", "https://pubmed.ncbi.nlm.nih.gov/26039521/"),
    module("fh-screen", "risk-stratification", "Familial hypercholesterolemia 의심", "LDL-C가 매우 높거나 조기 ASCVD 가족력이 있으면 FH를 의심한다.", ["LDL-C >=190 mg/dL은 단순 수치가 아니라 lifetime exposure 신호다.", "가족 선별, tendon xanthoma, 조기 CAD history를 질문한다.", "목표 미달 시 병용과 injectable escalation 가능성이 커진다."], "FH에서는 로수젯이 oral combination 단계의 한 축이지만, 중증 FH 전체 솔루션처럼 말하지 않는다.", "KSoLA/ESC FH framework", "https://www.escardio.org/guidelines"),
    module("ascvd-very-high", "risk-stratification", "Very high-risk ASCVD", "최근 ACS, 반복 사건, 다혈관질환, 당뇨병 동반 ASCVD는 낮은 LDL-C 목표가 적용된다.", ["목표 LDL-C와 baseline gap을 수치로 보여주면 intensification 필요성이 선명해진다.", "고강도 statin 단독으로 충분한지, ezetimibe 병용이 필요한지 묻는다.", "outcome 근거와 lipid efficacy 근거를 분리해 말한다."], "RACING은 ASCVD에서 moderate statin+ezetimibe 전략을 논의할 때 핵심 인접 근거다.", "RACING trial", "https://pubmed.ncbi.nlm.nih.gov/35863366/"),
    module("diabetes-risk", "risk-stratification", "당뇨병 환자의 risk layer", "당뇨병은 duration, target organ damage, ASCVD 동반 여부에 따라 LDL-C 목표가 달라진다.", ["T2DM+ASCVD는 매우 높은 위험군으로 접근한다.", "T2DM without ASCVD도 추가 risk factor에 따라 적극 치료가 필요하다.", "glycemic control과 lipid control을 별도 목표로 본다."], "EROICA는 T2DM에서 로수젯 lipid efficacy를 다룰 때 직접 근거 후보로 묶는다.", "ADA Standards of Care", "https://diabetesjournals.org/care"),
    module("ckd-risk", "risk-stratification", "CKD와 이상지질혈증", "CKD는 ASCVD risk enhancer이며 eGFR 단계와 albuminuria에 따라 위험도가 커진다.", ["신기능에 따른 rosuvastatin 용량 주의가 필요하다.", "투석 환자에서 신규 statin 시작 근거는 일반 ASCVD와 다르게 읽는다.", "SHARP는 simvastatin+ezetimibe CKD outcome 근거로 자주 언급된다."], "CKD 질문에서는 로수젯 용량과 신기능 주의사항을 허가사항 기준으로 확인한다.", "SHARP/KDIGO lipid evidence", "https://pubmed.ncbi.nlm.nih.gov/21663949/"),
    module("stroke-risk", "risk-stratification", "허혈성 뇌졸중/TIA 이후", "뇌졸중 이후 LDL-C lowering은 재발 예방 전략의 일부다.", ["SPARCL은 atorvastatin 고용량 stroke outcome 근거다.", "ROSETTA-Stroke는 rosuvastatin+ezetimibe 인접 전략 자료로 분리해 읽는다.", "출혈성 뇌졸중 이력 등 안전성 질문은 단순화하지 않는다."], "신경과 메시지는 LDL-C 목표 도달과 재발위험 관리를 중심에 둔다.", "SPARCL/ROSETTA-Stroke", "https://pubmed.ncbi.nlm.nih.gov/16899775/"),
    module("secondary-causes", "risk-stratification", "Secondary dyslipidemia 체크리스트", "갑상선기능저하, nephrotic syndrome, 간질환, 약물, 음주, 식이가 LDL/TG 상승의 원인이 될 수 있다.", ["약물 intensification 전 원인 교정을 확인한다.", "TG 급상승은 pancreatitis risk까지 따로 판단한다.", "PM 자료에는 진단 체크리스트를 넣되 치료 결정 알고리즘으로 포장하지 않는다."], "field 질문에서 목표 미달 원인 분석을 돕는 배경 지식이다.", "KSoLA dyslipidemia guideline", "https://new.lipid.or.kr/reference/guideline.php?boardid=guideline&category=&idx=1281&mode=view"),
    module("ksola-targets", "guideline-workflow", "KSoLA 목표치 읽는 순서", "국내 실행은 KSoLA 위험군 분류와 LDL-C 목표를 우선 확인한다.", ["ASCVD, 당뇨병, CKD, FH 등 risk category부터 정한다.", "LDL-C 목표와 baseline gap을 계산한다.", "생활습관, statin intensity, 병용 필요성을 순차로 본다."], "국내 PM 자료의 메인 backbone은 KSoLA로 두는 것이 자연스럽다.", "KSoLA guideline page", "https://new.lipid.or.kr/reference/guideline.php?boardid=guideline&category=&idx=1281&mode=view"),
    module("esc-2025", "guideline-workflow", "ESC/EAS 2025 Focused Update 포인트", "ESC/EAS는 lower LDL-C target과 nonstatin evidence framing을 강하게 제공한다.", ["very high-risk에서 엄격한 LDL-C 목표를 강조한다.", "PCSK9, bempedoic acid, inclisiran 같은 update를 함께 본다.", "한국 허가/급여/가이드라인과 직접 동일시하지 않는다."], "global KOL discussion에서는 ESC language가 메시지 방향을 정교하게 해준다.", "ESC dyslipidaemia guidelines", "https://www.escardio.org/guidelines/clinical-practice-guidelines/all-esc-practice-guidelines/dyslipidaemias/"),
    module("acc-aha-2026", "guideline-workflow", "ACC/AHA 2026 threshold 방식", "ACC/AHA는 risk group별 LDL-C threshold와 치료 intensification 흐름을 강조한다.", ["target number와 threshold language를 혼동하지 않는다.", "shared decision making, risk discussion, nonstatin add-on 기준을 같이 읽는다.", "미국 지침은 국내 지침의 보조 비교축이다."], "PM 메시지에서는 KSoLA 목표치와 ACC/AHA threshold를 구분해 설명한다.", "AHA professional guideline page", "https://professional.heart.org/en/science-news/2026-guideline-on-the-management-of-dyslipidemia"),
    module("monitoring-cycle", "guideline-workflow", "치료 후 monitoring cycle", "치료 시작 또는 변경 후 LDL-C 반응과 순응도를 재확인하는 주기가 필요하다.", ["baseline lipid panel, ALT, CK risk context를 확인한다.", "4-12주 재평가 개념은 intensification 대화에 유용하다.", "수치 미달은 efficacy, adherence, secondary cause로 나누어 본다."], "로수젯 전환/추가 후 follow-up lipid check 메시지를 교육 흐름에 넣는다.", "ACC/AHA cholesterol guidance", "https://professional.heart.org/"),
    module("statin-intensity", "treatment", "Statin intensity 표준 언어", "고강도 statin은 LDL-C를 대략 50% 이상, 중등도는 30-49% 낮추는 범주로 설명된다.", ["rosuvastatin 20-40 mg과 atorvastatin 40-80 mg은 고강도 범주다.", "용량 숫자만 비교하지 말고 intensity category로 말한다.", "부작용 우려가 있으면 증량보다 병용 전략 논의가 생긴다."], "로수젯 10/10 또는 10/20은 statin intensity와 ezetimibe 병용 효과를 함께 설명해야 한다.", "ACC/AHA statin intensity table", "https://professional.heart.org/"),
    module("ezetimibe-mechanism", "treatment", "Ezetimibe 10 mg의 역할", "NPC1L1을 통해 장 콜레스테롤 흡수를 억제해 statin과 상보적이다.", ["statin은 간 합성 억제, ezetimibe는 장 흡수 억제 축이다.", "statin 단독 목표 미달에서 add-on으로 실무 활용성이 높다.", "IMPROVE-IT은 ezetimibe outcome 근거의 핵심 anchor다."], "로수젯은 두 기전을 한 알로 묶어 adherence와 intensification 메시지를 만들 수 있다.", "IMPROVE-IT", "https://pubmed.ncbi.nlm.nih.gov/26039521/"),
    module("rosuzet-ladder", "treatment", "로수젯 용량 ladder", "로수젯은 ezetimibe 10 mg에 rosuvastatin 2.5/5/10/20 mg을 결합한 FDC다.", ["10/2.5는 statin 부담을 낮추고 병용을 시작하는 맥락으로 읽는다.", "10/5와 10/10은 중등도 statin+ezetimibe 전략의 중심이다.", "10/20은 높은 LDL-C gap에서 강한 oral option으로 포지셔닝된다."], "용량별 메시지는 허가사항, 목표 LDL-C gap, 환자 특성, 안전성 질문으로 나눠야 한다.", "Rosuzet label and WHO ATC", "https://atcddd.fhi.no/atc_ddd_index/?code=C10BA06"),
    module("racing-strategy", "treatment", "RACING으로 읽는 병용 전략", "ASCVD 환자에서 rosuvastatin 10 mg+ezetimibe 10 mg 전략을 고강도 rosuvastatin과 비교한 3년 연구다.", ["noninferiority, LDL-C target achievement, intolerance/discontinuation을 같이 본다.", "제품 직접 연구가 아니라 전략 근거로 분류한다.", "모든 환자에서 우월하다는 표현은 피한다."], "로수젯 메시지는 RACING을 'moderate statin+ezetimibe strategy' 근거로 안전하게 연결한다.", "RACING trial", "https://pubmed.ncbi.nlm.nih.gov/35863366/"),
    module("eroica-study", "treatment", "EROICA 연구 위치", "EROICA는 T2DM 환자에서 rosuvastatin/ezetimibe FDC lipid efficacy를 다루는 로수젯 직접 근거 후보로 관리한다.", ["endpoint가 lipid efficacy인지 clinical outcome인지 구분한다.", "HbA1c·공복혈당 변화와 safety table을 함께 확인한다.", "T2DM 전체 outcome claim으로 확대하지 않는다."], "EROICA는 endocrinology segment에서 직접성 높은 자료지만 단기 혈당 변화와 claim guardrail을 함께 설명해야 한다.", "PubMed publication 확인", "https://pubmed.ncbi.nlm.nih.gov/41190361/"),
    module("pcsk9-role", "treatment", "PCSK9 inhibitor의 위치", "evolocumab/alirocumab은 매우 큰 LDL-C lowering과 outcome 근거를 가진 injectable 옵션이다.", ["FOURIER와 ODYSSEY OUTCOMES는 outcome anchor다.", "가격, 급여, 주사제 수용성, residual gap이 실무 barrier다.", "oral FDC와 경쟁이면서 escalation 후속 옵션이다."], "로수젯은 PCSK9 이전 oral intensification 또는 병용 기반 치료 흐름에서 위치를 잡는다.", "FOURIER/ODYSSEY", "https://pubmed.ncbi.nlm.nih.gov/28304224/"),
    module("inclisiran", "treatment", "Inclisiran: siRNA adherence angle", "PCSK9 synthesis를 억제하는 siRNA로 긴 투여 간격이 특징이다.", ["LDL-C lowering 근거와 hard outcome 근거 성숙도를 구분한다.", "투여 간격은 adherence 메시지지만 국내 접근성은 별도 확인한다.", "statin/ezetimibe 기반 위에 올라가는 치료축이다."], "장기 순응도 논의에서 oral FDC와 injectable long-interval option을 비교한다.", "ORION program", "https://pubmed.ncbi.nlm.nih.gov/?term=inclisiran+ORION+LDL"),
    module("bempedoic-acid", "treatment", "Bempedoic acid: statin intolerance 대화", "ACL inhibitor로 statin intolerance 환자에서 LDL-C lowering과 CLEAR Outcomes 근거가 있다.", ["근육 관련 이상반응 우려 환자에서 질문이 나온다.", "gout, tendon rupture 등 safety signal을 같이 본다.", "국내 허가/급여 상태를 별도 확인해야 한다."], "statin intolerance objection에서 로수젯만으로 닫지 말고 치료 landscape를 보여준다.", "CLEAR Outcomes", "https://pubmed.ncbi.nlm.nih.gov/36876740/"),
    module("sams", "safety", "SAMS 평가", "statin-associated muscle symptoms는 causality 평가와 재도전 전략이 핵심이다.", ["증상 시점, CK, 운동, 갑상선, 상호작용을 확인한다.", "중단만이 답이 아니라 용량 조정, 다른 statin, 병용 전략이 있다.", "nocebo effect와 실제 myopathy를 구분한다."], "로수젯 저용량 조합은 statin 부담 질문에 대응할 수 있으나 안전성 우월 claim은 금지다.", "Statin safety consensus", "https://pubmed.ncbi.nlm.nih.gov/?term=statin+associated+muscle+symptoms+consensus"),
    module("liver-enzyme", "safety", "간효소 상승 대응", "statin 사용 중 ALT/AST 상승은 정도, 증상, 다른 원인을 함께 봐야 한다.", ["baseline liver disease와 alcohol history가 중요하다.", "경미한 상승을 자동 중단 사유로 단순화하지 않는다.", "황달, 증상, 현저한 상승은 의료진 판단 영역이다."], "PM 자료에는 모니터링 원칙만 넣고 개별 환자 처치처럼 쓰지 않는다.", "FDA/statin label safety", "https://www.accessdata.fda.gov/"),
    module("diabetes-signal", "safety", "Statin과 당뇨병 발생 signal", "고강도 statin에서 신규 당뇨병 위험 증가 signal이 보고되지만 ASCVD benefit과 균형 평가가 필요하다.", ["Sattar meta-analysis는 이 질문의 landmark다.", "T2DM 고위험군에서도 statin benefit을 같이 설명한다.", "혈당 관리는 중단 논리보다 monitoring 논리로 연결한다."], "T2DM PM 메시지에서 당뇨병 signal을 숨기지 말고 benefit-risk로 구조화한다.", "Sattar meta-analysis", "https://pubmed.ncbi.nlm.nih.gov/20167359/"),
    module("renal-dose", "safety", "신기능과 rosuvastatin", "rosuvastatin은 신기능 저하에서 노출 증가와 용량 주의가 논의된다.", ["eGFR 단계별 주의사항은 허가사항으로 확인한다.", "고령 CKD 환자는 muscle symptom과 polypharmacy 질문이 같이 나온다.", "CKD outcome 근거와 제품 용량 safety를 분리한다."], "로수젯 고용량 논의 전 renal function 질문을 field script에 넣는다.", "Rosuvastatin label", "https://www.accessdata.fda.gov/"),
    module("drug-interaction", "safety", "상호작용 체크", "cyclosporine, gemfibrozil, 일부 antivirals 등은 statin exposure와 myopathy risk에 영향을 줄 수 있다.", ["복약리스트 확인은 고령/CKD/이식/감염질환 환자에서 중요하다.", "fibrate 병용은 TG 맥락과 safety를 함께 본다.", "제품 claim보다 medication review 질문이 우선이다."], "field 대응 자료에 '현재 복용 약 확인'을 고정 질문으로 넣는다.", "Statin label safety", "https://www.accessdata.fda.gov/"),
    module("pregnancy", "safety", "임신·수유와 지질저하제", "임신 가능성, 임신, 수유에서는 statin/ezetimibe 사용 판단이 매우 보수적이다.", ["제품 허가사항과 전문의 판단이 우선이다.", "가임기 여성 상담은 contraception, pregnancy plan 확인이 필요하다.", "PM 자료에서는 일반적 금기/주의 수준으로 제한한다."], "이 주제는 세일즈 메시지가 아니라 medical safety guardrail로 취급한다.", "Product label safety", "https://nedrug.mfds.go.kr/"),
    module("older-adults", "special-populations", "고령 환자", "고령에서는 ASCVD benefit, frailty, polypharmacy, renal function, muscle symptom을 함께 본다.", ["나이만으로 치료 강도를 결정하지 않는다.", "secondary prevention benefit은 여전히 중요하다.", "복약 단순화는 FDC의 실무적 장점으로 논의할 수 있다."], "고령 환자에서는 adherence와 safety monitoring의 균형을 메시지 중심에 둔다.", "ACC/AHA older adult guidance", "https://professional.heart.org/"),
    module("acs-pathway", "special-populations", "ACS 퇴원 후 pathway", "ACS 이후에는 빠른 LDL-C lowering과 목표 도달 확인이 중요하다.", ["early intensive therapy와 follow-up lipid check가 핵심이다.", "IMPROVE-IT, PROVE-IT, MIRACL은 근거 축이다.", "퇴원 처방, 외래 재평가, 목표 미달 시 add-on을 연결한다."], "심장내과 메시지는 discharge-to-target workflow로 설계한다.", "ACS lipid trials", "https://pubmed.ncbi.nlm.nih.gov/11277825/"),
    module("t2dm-endocrine", "special-populations", "내분비내과 T2DM segment", "T2DM 환자는 LDL-C, TG, non-HDL-C, adherence가 동시에 이슈가 된다.", ["ASCVD 동반 여부와 target organ damage를 먼저 확인한다.", "EROICA는 lipid efficacy 직접 근거로 관리한다.", "혈당과 statin diabetes signal 질문에 대비한다."], "내분비내과에서는 'LDL-C 목표 미달 + 복약 단순화'를 중심으로 대화한다.", "ADA/KSoLA/EROICA", "https://diabetesjournals.org/care"),
    module("post-stroke", "special-populations", "뇌졸중 이후 lipid control", "허혈성 뇌졸중/TIA 환자는 recurrent event prevention 맥락에서 LDL-C 관리가 중요하다.", ["SPARCL, Treat Stroke to Target, ROSETTA-Stroke를 구분한다.", "출혈성 뇌졸중 우려 질문은 과장 없이 다룬다.", "neurology segment에는 재발위험과 목표 도달을 숫자로 보여준다."], "신경과용 자료는 'stroke outcome 근거'와 'rosuvastatin+ezetimibe 전략'을 구분한다.", "Stroke lipid evidence", "https://pubmed.ncbi.nlm.nih.gov/?term=Treat+Stroke+to+Target+LDL"),
    module("atc-who", "market", "WHO ATC C10BA06", "WHO ATC에서 rosuvastatin and ezetimibe는 C10BA06로 분류된다.", ["C10은 lipid modifying agents다.", "C10B는 combination lipid modifying agents다.", "C10BA06은 성분 조합 코드이지 시장 세그먼트 점유율 코드가 아니다."], "자료 첫 장에서 C10BA06과 C10C를 분리하면 분류 혼선을 줄인다.", "WHO ATC/DDD index", "https://atcddd.fhi.no/atc_ddd_index/?code=C10BA06"),
    module("ephmra-c10c", "market", "EPHMRA/Intellus C10C", "C10C는 시장 데이터에서 lipid regulators in combination with other lipid regulators를 의미한다.", ["WHO ATC와 naming이 비슷해 혼동이 잦다.", "시장자료, IMS/IQVIA류 dashboard, competitor map에서 쓰는 lens다.", "규제/허가 분류처럼 말하지 않는다."], "로수젯 PM은 C10BA06과 C10C를 모두 알아야 시장/의학 대화가 정리된다.", "EPHMRA classification reference", "https://www.ephmra.org/"),
    module("patient-funnel", "market", "환자 funnel 설계", "prevalent dyslipidemia, diagnosed, treated, statin mono, goal failure, FDC candidate로 단계화한다.", ["각 단계의 가정 출처를 명시해야 한다.", "TAM/SAM/SOM은 환자 수와 처방 가치 두 버전으로 만든다.", "진단률과 치료율은 KSoLA fact sheet 업데이트를 확인한다."], "market sizing 계산기의 가정을 분기별로 검토하는 PM routine을 만든다.", "KSoLA Dyslipidemia Fact Sheet", "https://www.lipid.or.kr/"),
    module("competitor-map", "market", "경쟁구도 분류", "동일성분 FDC, 타 statin+ezetimibe, 고강도 statin, injectable, TG 치료제를 같은 축에 놓지 않는다.", ["동일성분은 가격/브랜드/공급 안정성 질문이다.", "타 FDC는 statin identity와 용량 line-up 질문이다.", "injectable은 목표 미달 중증 환자 escalation 질문이다."], "경쟁 대응은 class별로 objection bank를 다르게 써야 한다.", "Internal market taxonomy", "https://www.ephmra.org/"),
    module("kol-map", "market", "KOL 질문 맵", "KOL은 지침, outcome, safety, real-world, 환자 세그먼트별로 다른 질문을 던진다.", ["심장내과는 ASCVD outcome과 target attainment를 본다.", "내분비내과는 T2DM safety와 lipid efficacy를 묻는다.", "신경과는 stroke recurrence 근거를 요구한다."], "KOL visit 전 질문 예상표를 evidence atlas와 연결한다.", "PM planning framework", "https://pubmed.ncbi.nlm.nih.gov/35863366/"),
    module("claim-ladder", "field", "Claim ladder", "mechanism, lipid lowering, target attainment, outcome, superiority를 서로 다른 등급으로 다룬다.", ["제품 직접 lipid study로 outcome claim을 만들지 않는다.", "strategy outcome study를 브랜드 우월성으로 확대하지 않는다.", "허가사항 문구와 논문 문구를 분리한다."], "자료 검수 시 문장마다 claim level을 표시하면 리스크가 줄어든다.", "Claim guardrail framework", "https://pubmed.ncbi.nlm.nih.gov/26039521/"),
    module("objection-generic", "field", "제네릭/동일성분 반론", "동일성분 경쟁은 efficacy보다 신뢰, 공급, line-up, 자료 품질, 교육 지원의 경쟁이다.", ["동일성분 간 임상 우월 claim은 피한다.", "로수젯 자산과 근거 구조화의 품질로 차별화한다.", "가격 질문은 회사 정책과 채널 기준에 맞춘다."], "MR/MSL 교육에는 '동일성분 우월' 금지 문구를 넣는다.", "PM claim hygiene", "https://nedrug.mfds.go.kr/"),
    module("objection-high-statin", "field", "고강도 statin 단독이면 충분한가", "질문을 LDL-C gap, tolerability, target attainment, outcome strategy로 분해한다.", ["고강도 statin은 중요한 표준치료다.", "목표 미달 또는 tolerability 이슈에서는 ezetimibe 병용이 논리적이다.", "RACING은 병용 전략 근거이나 모든 상황의 대체 논리는 아니다."], "답변은 '대체'가 아니라 '목표 도달을 위한 선택지'로 구성한다.", "RACING/ACC guidance", "https://pubmed.ncbi.nlm.nih.gov/35863366/"),
    module("field-call-flow", "field", "3분 call flow", "환자군 질문, 목표 미달 수치, 치료 option, 근거 anchor, follow-up action 순서로 짧게 말한다.", ["첫 질문은 '어떤 환자가 목표 미달인가'로 시작한다.", "두 번째는 '현재 statin 강도와 순응도'다.", "마지막은 '다음 lipid check 시점'이다."], "단순 제품 소개보다 진료 흐름에 들어가는 질문형 메시지가 좋다.", "Field execution playbook", "https://professional.heart.org/"),
    module("pico", "evidence-reading", "PICO로 논문 쪼개기", "Population, Intervention, Comparator, Outcome을 분리하면 claim 가능 범위가 보인다.", ["Population 밖으로 일반화하지 않는다.", "surrogate endpoint와 clinical endpoint를 구분한다.", "comparator가 placebo인지 active인지에 따라 메시지가 달라진다."], "모든 로수젯 관련 논문 카드는 PICO부터 적는다.", "Evidence-based medicine basics", "https://pubmed.ncbi.nlm.nih.gov/"),
    module("endpoint", "evidence-reading", "Endpoint hierarchy", "LDL-C 변화, target attainment, MACE, mortality, safety discontinuation은 서로 다른 무게를 가진다.", ["lipid efficacy는 빠르게 읽히지만 outcome claim으로 직행할 수 없다.", "MACE composite 구성요소를 확인한다.", "safety endpoint는 이상반응, 중단, lab signal을 나눠 본다."], "자료에는 endpoint 등급을 시각적으로 표시한다.", "Clinical trial methods", "https://pubmed.ncbi.nlm.nih.gov/"),
    module("noninferiority", "evidence-reading", "Noninferiority 해석", "비열등 연구는 margin, population, adherence, event rate를 함께 읽어야 한다.", ["비열등은 우월과 다르다.", "per-protocol과 intention-to-treat 결과를 같이 확인한다.", "margin의 임상적 의미를 질문해야 한다."], "RACING 해석에서 이 모듈이 특히 중요하다.", "RACING methods", "https://pubmed.ncbi.nlm.nih.gov/35863366/"),
    module("subgroup", "evidence-reading", "Subgroup 읽기", "diabetes, elderly, CKD, prior PCI 같은 subgroup은 interaction p-value와 사전정의 여부가 중요하다.", ["subgroup 결과는 hypothesis-generating인지 확인한다.", "작은 표본의 과해석을 피한다.", "PM 메시지는 본 연구의 primary conclusion을 넘지 않는다."], "RACING diabetes subgroup 등은 segment 자료로 쓰되 claim 수위를 낮춘다.", "Subgroup interpretation", "https://pubmed.ncbi.nlm.nih.gov/37531130/"),
    module("rwe", "evidence-reading", "Real-world evidence", "claims/EHR 기반 RWE는 외적 타당성이 장점이지만 confounding과 coding limitation이 있다.", ["adherence, persistence, target attainment 분석에 유용하다.", "causal claim은 design과 보정 수준을 확인한다.", "국내 real-world data는 market access 자료와 연결된다."], "로수젯 RWE 아이디어는 처방 지속성, 목표 도달률, switching pattern으로 설계할 수 있다.", "RWE methods", "https://pubmed.ncbi.nlm.nih.gov/"),
    module("mace", "glossary", "MACE", "Major adverse cardiovascular events. 연구마다 구성요소가 다르므로 CV death, MI, stroke, revascularization 포함 여부를 확인한다.", ["동일한 MACE라도 연구 간 직접 비교는 어렵다.", "구성요소별 결과를 같이 본다.", "PM 슬라이드에는 definition footnote가 필요하다."], "outcome claim의 첫 번째 검수 포인트다.", "Trial endpoint convention", "https://pubmed.ncbi.nlm.nih.gov/"),
    module("hr-ci", "glossary", "HR과 95% CI", "Hazard ratio는 시간-사건 데이터를 비교하고, 95% confidence interval은 추정의 불확실성을 보여준다.", ["CI가 1을 포함하는지 확인한다.", "통계적 유의성과 임상적 의미는 다르다.", "상대위험과 절대위험 감소를 같이 봐야 한다."], "KOL 대응에서 숫자를 과장하지 않게 해준다.", "Clinical trial statistics", "https://pubmed.ncbi.nlm.nih.gov/"),
    module("nnt", "glossary", "NNT", "Number needed to treat는 특정 기간 동안 사건 하나를 예방하기 위해 치료해야 하는 환자 수다.", ["baseline risk가 높을수록 NNT는 좋아진다.", "연구 기간과 population을 항상 붙인다.", "relative risk reduction만 말하면 실제 impact가 부풀 수 있다."], "ASCVD very high-risk 자료에서 absolute benefit을 설명하는 도구다.", "Evidence interpretation", "https://pubmed.ncbi.nlm.nih.gov/"),
    module("treat-target", "glossary", "Treat-to-target", "정해진 LDL-C 목표에 도달하도록 치료를 조정하는 접근이다.", ["KSoLA/ESC target 문법과 잘 맞는다.", "ACC/AHA threshold 문법과는 용어를 구분한다.", "follow-up lipid check가 필수다."], "로수젯은 target gap을 줄이는 oral FDC option으로 설명한다.", "Guideline terminology", "https://www.escardio.org/guidelines"),
    module("residual-risk", "glossary", "Residual risk", "LDL-C 치료 후에도 TG, Lp(a), inflammation, diabetes, hypertension 등으로 남는 위험이다.", ["residual risk를 이유로 LDL-C 관리를 약화하지 않는다.", "위험 인자별로 치료 옵션과 근거가 다르다.", "TG 치료제 claim과 LDL-C 치료제 claim을 분리한다."], "경쟁품/TG 질문에서 로수젯의 역할을 명확히 하는 개념이다.", "Residual risk review", "https://pubmed.ncbi.nlm.nih.gov/")
  ];

  function module(id, category, title, summary, learn, pmUse, sourceNote, sourceUrl) {
    return { id, category, title, summary, learn, pmUse, sourceNote, sourceUrl };
  }

  const normalize = (value) => String(value || "").toLocaleLowerCase("ko-KR");

  const moduleSearchText = (item) => {
    return normalize([item.title, item.summary, item.learn.join(" "), item.pmUse, item.sourceNote].join(" "));
  };

  const getModulesByCategory = (categoryId) => {
    if (!categoryId || categoryId === "all") {
      return [...libraryModules];
    }
    return libraryModules.filter((item) => item.category === categoryId);
  };

  const searchLibrary = (query) => {
    const needle = normalize(query);
    if (!needle) {
      return [...libraryModules];
    }
    return libraryModules.filter((item) => moduleSearchText(item).includes(needle));
  };

  const getModuleById = (id) => libraryModules.find((item) => item.id === id);

  const categoryCounts = libraryCategories.map((category) => ({
    id: category.id,
    count: getModulesByCategory(category.id).length
  }));

  globalThis.LibraryData = {
    categoryCounts,
    getModuleById,
    getModulesByCategory,
    libraryCategories,
    libraryModules,
    searchLibrary
  };
})();
